AUTHOR = 'Edgar L'
SITENAME = 'datacloudhero.com'
SITEURL = ""

PATH = "content"

THEME = "themes/mytheme"
AUTHORS_INFO = {
    'Edgar L': {
        'avatar': 'https://avatars.githubusercontent.com/u/78014277?v=4',
        'title': 'Technical Content Writer — AI & Data',
        'linkedin': 'https://www.linkedin.com/in/edgarlakshin/',
        'github': 'https://github.com/edgrln',
    },
    'Alina Lane': {
        'avatar': 'https://avatars.githubusercontent.com/u/253337931?v=4',
        'title': 'Founder datacloud.com',
        'linkedin': 'https://www.linkedin.com/in/edgarlakshin/',
        'github': 'https://github.com/edgrln',
    },
}

CTA_TITLE = "Let's build something great"
CTA_TEXT = "Опишите вашу задачу — обсудим без лишних продаж, чисто по делу."
CTA_BUTTON_TEXT = "Написать"
CTA_BUTTON_LINK = "mailto:you@example.com"
CTA_FOOTNOTE = "you@example.com · Работаю удалённо"

TIMEZONE = 'Europe/Rome'

DEFAULT_LANG = 'En'

# Feed generation is usually not desired when developing
FEED_ALL_ATOM = None
CATEGORY_FEED_ATOM = None
TRANSLATION_FEED_ATOM = None
AUTHOR_FEED_ATOM = None
AUTHOR_FEED_RSS = None

# Blogroll
LINKS = [
    ("Cookie Policy", "#"),
    ("Cookie settings", "#"),
]

# Social widget
SOCIAL = [
    ("Git Hub", "https://github.com/edgrln/datacloudhero_v2"),
]

DEFAULT_PAGINATION = 10

# Clean stale files (e.g. old *.html paths) before each build
DELETE_OUTPUT_DIRECTORY = True

# All blog content lives under /blog/ — the site root is a separate static
# landing page (see STATIC_PATHS below), not generated by Pelican.
ARTICLE_URL = 'blog/{slug}/'
ARTICLE_SAVE_AS = 'blog/{slug}/index.html'
PAGE_URL = 'blog/{slug}/'
PAGE_SAVE_AS = 'blog/{slug}/index.html'
AUTHOR_URL = 'blog/author/{slug}/'
AUTHOR_SAVE_AS = 'blog/author/{slug}/index.html'
CATEGORY_URL = 'blog/category/{slug}/'
CATEGORY_SAVE_AS = 'blog/category/{slug}/index.html'
TAG_URL = 'blog/tag/{slug}/'
TAG_SAVE_AS = 'blog/tag/{slug}/index.html'

INDEX_SAVE_AS = 'blog/index.html'
TAGS_SAVE_AS = 'blog/tags.html'
TAGS_URL = 'blog/tags.html'
CATEGORIES_SAVE_AS = 'blog/categories.html'
CATEGORIES_URL = 'blog/categories.html'
AUTHORS_SAVE_AS = 'blog/authors.html'
AUTHORS_URL = 'blog/authors.html'
ARCHIVES_SAVE_AS = 'blog/archives.html'
ARCHIVES_URL = 'blog/archives.html'

# Client-side search index (see themes/mytheme/templates/search.html)
DIRECT_TEMPLATES = ["index", "tags", "categories", "authors", "archives", "search"]
SEARCH_SAVE_AS = "blog/search-index.json"
SEARCH_URL = "blog/search-index.json"

# Landing page: a self-contained static HTML file copied verbatim to the
# site root (it is not run through the blog theme/templates at all).
STATIC_PATHS = ['extra/index.html']
EXTRA_PATH_METADATA = {
    'extra/index.html': {'path': 'index.html'},
}
# Keep the article/page generators from also trying to parse it as content
ARTICLE_EXCLUDES = ['extra']
PAGE_EXCLUDES = ['extra']

import json as _json
JINJA_FILTERS = {"tojson": _json.dumps}

# --- Markdown mirrors (Stripe-style /docs/foo.md) --------------------------
# Alongside every rendered blog/{slug}/index.html, write a plain
# blog/{slug}.md containing the article's raw Markdown body. This gives
# LLMs/scrapers/"copy as markdown" buttons a clean source to fetch instead
# of having to parse the HTML page.
import os as _os
import re as _re

_METADATA_LINE_RE = _re.compile(r'^[A-Za-z][\w ]*:\s')


def _strip_pelican_metadata(raw_text):
    """Return the article body, with the leading `Key: value` metadata
    block (Title/Date/Author/...) that Pelican reads off the top of a
    Markdown source file removed."""
    lines = raw_text.splitlines()
    body_start = 0
    for idx, line in enumerate(lines):
        if not line.strip():
            body_start = idx + 1
            break
        if not _METADATA_LINE_RE.match(line):
            # Doesn't look like a metadata block at all - keep everything.
            body_start = 0
            break
    else:
        body_start = len(lines)
    return "\n".join(lines[body_start:]).strip() + "\n"


def _write_markdown_mirrors(article_generator):
    site_url = article_generator.settings.get('SITEURL', '') or ''
    for article in article_generator.articles:
        source_path = getattr(article, 'source_path', None)
        if not source_path or not _os.path.exists(source_path):
            continue

        with open(source_path, encoding='utf-8') as f:
            body = _strip_pelican_metadata(f.read())

        canonical = f"{site_url}/{article.url}" if site_url else f"/{article.url}"
        header = (
            f"# {article.title}\n\n"
            f"> Source: {canonical}\n"
            f"> Published: {article.date:%Y-%m-%d}\n\n"
        )

        # blog/{slug}/index.html -> blog/{slug}.md
        md_relpath = _os.path.dirname(article.save_as) + '.md'
        md_path = _os.path.join(article_generator.output_path, md_relpath)
        _os.makedirs(_os.path.dirname(md_path), exist_ok=True)
        with open(md_path, 'w', encoding='utf-8') as f:
            f.write(header + body)


from pelican import signals as _signals
_signals.article_generator_finalized.connect(_write_markdown_mirrors)

# Uncomment following line if you want document-relative URLs when developing
# RELATIVE_URLS = True
