AUTHOR = 'Edgar L'
SITENAME = 'datacloudhero.com'
SITEURL = ""

PATH = "content"

THEME = "themes/mytheme"
AUTHORS_INFO = {
    'Edgar L': {
        'avatar': 'https://avatars.githubusercontent.com/u/78014277?v=4',
        'title': 'Technical Content Writer — AI & Data',
        'linkedin': 'https://www.linkedin.com/in/edgarlakshin/',
        'github': 'https://github.com/edgrln',
    },
    'Alina Lane': {
        'avatar': 'https://avatars.githubusercontent.com/u/253337931?v=4',
        'title': 'Founder datacloud.com',
        'linkedin': 'https://www.linkedin.com/in/edgarlakshin/',
        'github': 'https://github.com/edgrln',
    },
}

CTA_TITLE = "Let's build something great"
CTA_TEXT = "Опишите вашу задачу — обсудим без лишних продаж, чисто по делу."
CTA_BUTTON_TEXT = "Написать"
CTA_BUTTON_LINK = "mailto:you@example.com"
CTA_FOOTNOTE = "you@example.com · Работаю удалённо"

TIMEZONE = 'Europe/Rome'

DEFAULT_LANG = 'En'

# Feed generation is usually not desired when developing
FEED_ALL_ATOM = None
CATEGORY_FEED_ATOM = None
TRANSLATION_FEED_ATOM = None
AUTHOR_FEED_ATOM = None
AUTHOR_FEED_RSS = None

# Blogroll
LINKS = [
    ("Cookie Policy", "#"),
    ("Cookie settings", "#"),
]

# Social widget
SOCIAL = [
    ("Git Hub", "https://github.com/edgrln/datacloudhero_v2"),
]

DEFAULT_PAGINATION = 10

# Clean stale files (e.g. old *.html paths) before each build
DELETE_OUTPUT_DIRECTORY = True

# All blog content lives under /blog/ — the site root is a separate static
# landing page (see STATIC_PATHS below), not generated by Pelican.
ARTICLE_URL = 'blog/{slug}/'
ARTICLE_SAVE_AS = 'blog/{slug}/index.html'
PAGE_URL = 'blog/{slug}/'
PAGE_SAVE_AS = 'blog/{slug}/index.html'
AUTHOR_URL = 'blog/author/{slug}/'
AUTHOR_SAVE_AS = 'blog/author/{slug}/index.html'
CATEGORY_URL = 'blog/category/{slug}/'
CATEGORY_SAVE_AS = 'blog/category/{slug}/index.html'
TAG_URL = 'blog/tag/{slug}/'
TAG_SAVE_AS = 'blog/tag/{slug}/index.html'

INDEX_SAVE_AS = 'blog/index.html'
TAGS_SAVE_AS = 'blog/tags.html'
TAGS_URL = 'blog/tags.html'
CATEGORIES_SAVE_AS = 'blog/categories.html'
CATEGORIES_URL = 'blog/categories.html'
AUTHORS_SAVE_AS = 'blog/authors.html'
AUTHORS_URL = 'blog/authors.html'
ARCHIVES_SAVE_AS = 'blog/archives.html'
ARCHIVES_URL = 'blog/archives.html'

# Client-side search index (see themes/mytheme/templates/search.html)
DIRECT_TEMPLATES = ["index", "tags", "categories", "authors", "archives", "search"]
SEARCH_SAVE_AS = "blog/search-index.json"
SEARCH_URL = "blog/search-index.json"

# Landing page: a self-contained static HTML file copied verbatim to the
# site root (it is not run through the blog theme/templates at all).
STATIC_PATHS = ['extra/index.html']
EXTRA_PATH_METADATA = {
    'extra/index.html': {'path': 'index.html'},
}
# Keep the article/page generators from also trying to parse it as content
ARTICLE_EXCLUDES = ['extra']
PAGE_EXCLUDES = ['extra']

import json as _json
JINJA_FILTERS = {"tojson": _json.dumps}

# Uncomment following line if you want document-relative URLs when developing
# RELATIVE_URLS = True
